from PyQt4.QtGui import *
from PyQt4.QtCore import *
from CustomPyQt import *

class BarOptions():
    def __init__(self):
        # cria os botões da barra de opções
        
        self.win = None
        self.main_buttonIN = QPushButton('Novo Compromisso')
        self.main_buttonOUT = QPushButton('Cancelar')
        self.buttonConfig = QPushButton('Perfil')
        self.buttonSetOK = QPushButton('OK')
        self.separator1 = QWidget()
        self.separator2 = QWidget()
        
        # cria barra para escrever o título do compromisso
        self.Title = QLineEdit()
        self.Title.setPlaceholderText('Título')
        self.endereco = QLineEdit()
        self.endereco.setPlaceholderText('Local.ex.:SP,São Paulo,Rua,n°')
        self.Descricao = CustomTextEdit('Descrição')
        self.optionFixo = QRadioButton('Fixo')
        self.optionFlexivel = QRadioButton('Flexível')
        
        self.repetir = QComboBox()
        self.repetirLabel = QLabel('Repetir')
        self.repetir.addItems(['Nunca','Todo Dia','Toda Semana','Todo Mês'])
        self.transporte = QComboBox()
        self.transporteLabel = QLabel('Transporte')
        self.transporte.addItems(['A Pé','Bicicleta','Carro','Moto','Metrô','Ônibus'])
        self.inicioLabel = QLabel('Horário de Início')
        self.inicioTime = QTimeEdit()
        self.inicioTime.setDisplayFormat('HH:mm')
        self.inicioDate = QDateEdit()
        self.terminoLabel = QLabel('Horário de Término')
        self.terminoTime = QTimeEdit()
        self.terminoTime.setDisplayFormat('HH:mm')
        self.terminoDate = QDateEdit()
        self.allDay = QCheckBox('Dia todo')
        
        self.dataLimiteCheck = QCheckBox('Data limite')
        self.dataLimite = QDateEdit()
        self.dataLimite.setDisabled(True)
        self.spinDuracaoLabel = QLabel('Duração')
        self.spinDuracao = QTimeEdit()
        self.spinDuracao.setDisplayFormat('HH:mm')
        self.prioridade = QComboBox()
        self.prioridadeLabel = QLabel('Prioridade')
        self.prioridade.addItems(['Baixa','Média','Alta'])
        self.restricaoTimeCheck = QCheckBox('Restrição de horário')
        self.restricaoTimeDasLabel = QLabel('               Das:')
        self.restricaoTimeDas = QTimeEdit()
        self.restricaoTimeDas.setDisplayFormat('HH:mm')
        self.restricaoTimeDas.setDisabled(True)
        self.restricaoTimeAteLabel = QLabel('                 Às:')
        self.restricaoTimeAte = QTimeEdit()
        self.restricaoTimeAte.setDisplayFormat('HH:mm')
        self.restricaoTimeAte.setDisabled(True)
        self.restricaoDayOfWeekCheck = QCheckBox('Dias indisponíveis')
        self.restricaoSeg = CustomPushButton('S')
        self.restricaoSeg.setFunc('SELECT DAY')
        self.restricaoSeg.setDisabled(True)
        self.restricaoTer = CustomPushButton('T')
        self.restricaoTer.setFunc('SELECT DAY')
        self.restricaoTer.setDisabled(True)
        self.restricaoQua = CustomPushButton('Q')
        self.restricaoQua.setFunc('SELECT DAY')
        self.restricaoQua.setDisabled(True)
        self.restricaoQui = CustomPushButton('Q')
        self.restricaoQui.setFunc('SELECT DAY')
        self.restricaoQui.setDisabled(True)
        self.restricaoSex = CustomPushButton('S')
        self.restricaoSex.setFunc('SELECT DAY')
        self.restricaoSex.setDisabled(True)
        self.restricaoSab = CustomPushButton('S')
        self.restricaoSab.setFunc('SELECT DAY')
        self.restricaoSab.setDisabled(True)
        self.restricaoDom = CustomPushButton('D')
        self.restricaoDom.setFunc('SELECT DAY')
        self.restricaoDom.setDisabled(True)
        
        self.main_buttonIN.clicked.connect(self.showOptions)
        self.main_buttonOUT.clicked.connect(self.hideOptions)
        self.optionFixo.clicked.connect(self.checkFixoFlexivel)
        self.optionFlexivel.clicked.connect(self.checkFixoFlexivel)
        self.buttonConfig.clicked.connect(self.showConfig)
        self.dataLimiteCheck.clicked.connect(self.setDataLimite)
        self.restricaoTimeCheck.clicked.connect(self.setRestricaoTime)
        self.restricaoDayOfWeekCheck.clicked.connect(self.setRestricaoDayOfWeek)
        self.allDay.clicked.connect(self.setAllDay)
    
    def showOptions(self):
        self.main_buttonIN.hide()
        self.separator1.hide()
        self.separator2.hide()
        self.main_buttonOUT.show()
        
        self.Title.show()
        self.endereco.show()
        self.Descricao.show()
        self.optionFixo.show()
        self.optionFixo.setCheckable(True)
        self.optionFlexivel.show()
        self.optionFlexivel.setCheckable(True)
        
        self.buttonSetOK.show()
        
    
    def showConfig(self):
        self.hideOptions()
        self.main_buttonIN.hide()
        self.main_buttonOUT.show()
        self.separator1.hide()
        
        self.separator2.show()

    def hideOptions(self):
        self.main_buttonOUT.hide()
        self.main_buttonIN.show()
        self.separator1.show()
        self.separator2.hide()
        
        self.Title.hide()
        self.Title.clear()
        self.endereco.hide()
        self.endereco.clear()
        self.Descricao.hide()
        self.Descricao.setDefault()
        self.optionFixo.hide()
        self.optionFixo.setCheckable(False)
        self.optionFlexivel.hide()
        self.optionFlexivel.setCheckable(False)
        
        self.repetirLabel.hide()
        self.repetir.hide()
        self.repetir.setCurrentIndex(0)
        self.transporteLabel.hide()
        self.transporte.hide()
        self.transporte.setCurrentIndex(0)
        self.inicioLabel.hide()
        
        self.inicioDate.hide()
        self.inicioTime.hide()
        self.inicioTime.setDisabled(False)
        self.terminoLabel.hide()
        self.terminoDate.hide()
        self.terminoDate.setDisabled(False)
        self.terminoTime.hide()
        self.terminoTime.setDisabled(False)
        self.allDay.hide()
        self.allDay.setCheckable(False)
        
        self.spinDuracaoLabel.hide()
        self.spinDuracao.hide()
        self.spinDuracao.setTime(QTime(0,0))
        self.dataLimiteCheck.hide()
        self.dataLimiteCheck.setCheckable(False)
        self.dataLimite.hide()
        self.dataLimite.setDisabled(True)
        self.prioridadeLabel.hide()
        self.prioridade.hide()
        self.restricaoTimeCheck.hide()
        self.restricaoTimeCheck.setCheckable(False)
        self.restricaoTimeDasLabel.hide()
        self.restricaoTimeDas.hide()
        self.restricaoTimeDas.setDisabled(True)
        self.restricaoTimeAteLabel.hide()
        self.restricaoTimeAte.hide()
        self.restricaoTimeAte.setDisabled(True)
        self.restricaoDayOfWeekCheck.hide()
        self.restricaoDayOfWeekCheck.setCheckable(False)
        self.restricaoSeg.hide()
        self.restricaoSeg.setDisabled(True)
        self.restricaoTer.hide()
        self.restricaoTer.setDisabled(True)
        self.restricaoQua.hide()
        self.restricaoQua.setDisabled(True)
        self.restricaoQui.hide()
        self.restricaoQui.setDisabled(True)
        self.restricaoSex.hide()
        self.restricaoSex.setDisabled(True)
        self.restricaoSab.hide()
        self.restricaoSab.setDisabled(True)
        self.restricaoDom.hide()
        self.restricaoDom.setDisabled(True)
        
        self.buttonSetOK.hide()

    def checkFixoFlexivel(self):
        if self.optionFixo.isChecked():
            self.dataLimiteCheck.hide()
            self.dataLimiteCheck.setCheckable(False)
            self.dataLimite.hide()
            self.dataLimite.setDisabled(True)
            self.spinDuracaoLabel.hide()
            self.spinDuracao.hide()
            self.spinDuracao.setTime(QTime(0,0))
            self.prioridadeLabel.hide()
            self.prioridade.hide()
            self.prioridade.setCurrentIndex(0)
            self.restricaoTimeCheck.hide()
            self.restricaoTimeCheck.setCheckable(False)
            self.restricaoTimeDasLabel.hide()
            self.restricaoTimeDas.hide()
            self.restricaoTimeDas.setDisabled(True)
            self.restricaoTimeAteLabel.hide()
            self.restricaoTimeAte.hide()
            self.restricaoTimeAte.setDisabled(True)
            self.restricaoDayOfWeekCheck.hide()
            self.restricaoDayOfWeekCheck.setCheckable(False)
            self.restricaoSeg.hide()
            self.restricaoSeg.setDisabled(True)
            self.restricaoTer.hide()
            self.restricaoTer.setDisabled(True)
            self.restricaoQua.hide()
            self.restricaoQua.setDisabled(True)
            self.restricaoQui.hide()
            self.restricaoQui.setDisabled(True)
            self.restricaoSex.hide()
            self.restricaoSex.setDisabled(True)
            self.restricaoSab.hide()
            self.restricaoSab.setDisabled(True)
            self.restricaoDom.hide()
            self.restricaoDom.setDisabled(True)
            
            time = QTime.currentTime()
            nextTime = time.addSecs(3600)
            date = QDate.currentDate()
            
            self.repetirLabel.show()
            self.repetir.show()
            self.transporteLabel.show()
            self.transporte.show()
            self.inicioLabel.show()
            self.inicioDate.show()
            self.inicioDate.setDate(date)
            self.inicioTime.show()
            self.inicioTime.setTime(time)
            self.terminoLabel.show()
            self.terminoDate.show()
            if nextTime.hour() == 0:
                self.terminoDate.setDate(date.addDays(1))
            else:
                self.terminoDate.setDate(date)
            self.terminoTime.show()
            self.terminoTime.setTime(nextTime)
            self.allDay.show()
            self.allDay.setCheckable(True)
            
        elif self.optionFlexivel.isChecked():
            self.repetirLabel.hide()
            self.repetir.hide()
            self.repetir.setCurrentIndex(0)
            self.transporteLabel.hide()
            self.transporte.hide()
            self.transporte.setCurrentIndex(0)
            self.inicioLabel.hide()
            self.inicioDate.hide()
            self.inicioTime.hide()
            self.inicioTime.setDisabled(False)
            self.terminoLabel.hide()
            self.terminoDate.hide()
            self.terminoDate.setDisabled(False)
            self.terminoTime.hide()
            self.terminoTime.setDisabled(False)
            self.allDay.hide()
            self.allDay.setCheckable(False)
            
            date = QDate.currentDate()
            
            self.dataLimiteCheck.show()
            self.dataLimiteCheck.setCheckable(True)
            self.dataLimite.show()
            self.dataLimite.setDate(date.addDays(7))
            self.spinDuracaoLabel.show()
            self.spinDuracao.show()
            self.prioridadeLabel.show()
            self.prioridade.show()
            self.restricaoTimeCheck.show()
            self.restricaoTimeCheck.setCheckable(True)
            self.restricaoTimeDasLabel.show()
            self.restricaoTimeDas.show()
            self.restricaoTimeAteLabel.show()
            self.restricaoTimeAte.show()
            self.restricaoDayOfWeekCheck.show()
            self.restricaoDayOfWeekCheck.setCheckable(True)
            self.restricaoSeg.show()
            self.restricaoTer.show()
            self.restricaoQua.show()
            self.restricaoQui.show()
            self.restricaoSex.show()
            self.restricaoSab.show()
            self.restricaoDom.show()
    
    def setDataLimite(self):
        if self.dataLimiteCheck.isChecked():
            self.dataLimite.setDisabled(False)
        else:
            self.dataLimite.setDisabled(True)
            date = QDate.currentDate()
            self.dataLimite.setDate(date.addDays(7))
    
    def setRestricaoTime(self):
        if self.restricaoTimeCheck.isChecked():
            self.restricaoTimeAte.setDisabled(False)
            self.restricaoTimeDas.setDisabled(False)
        else:
            self.restricaoTimeAte.setDisabled(True)
            self.restricaoTimeAte.setTime(QTime(0,0))
            self.restricaoTimeDas.setDisabled(True)
            self.restricaoTimeDas.setTime(QTime(0,0))
    
    def setRestricaoDayOfWeek(self):
        if self.restricaoDayOfWeekCheck.isChecked():
            self.restricaoSeg.setDisabled(False)
            self.restricaoTer.setDisabled(False)
            self.restricaoQua.setDisabled(False)
            self.restricaoQui.setDisabled(False)
            self.restricaoSex.setDisabled(False)
            self.restricaoSab.setDisabled(False)
            self.restricaoDom.setDisabled(False)
        else:
            self.restricaoSeg.setDisabled(True)
            self.restricaoSeg.setDEFAULT()
            self.restricaoTer.setDisabled(True)
            self.restricaoTer.setDEFAULT()
            self.restricaoQua.setDisabled(True)
            self.restricaoQua.setDEFAULT()
            self.restricaoQui.setDisabled(True)
            self.restricaoQui.setDEFAULT()
            self.restricaoSex.setDisabled(True)
            self.restricaoSex.setDEFAULT()
            self.restricaoSab.setDisabled(True)
            self.restricaoSab.setDEFAULT()
            self.restricaoDom.setDisabled(True)
            self.restricaoDom.setDEFAULT()
    
    def setAllDay(self):
        time = QTime.currentTime()
        nextTime = time.addSecs(3600)
        date = QDate.currentDate()
        
        if self.allDay.isChecked():
            self.inicioTime.setDisabled(True)
            self.inicioTime.setTime(time)
            self.terminoDate.setDisabled(True)
            if nextTime.hour() == 0:
                self.terminoDate.setDate(date.addDays(1))
            else:
                self.terminoDate.setDate(date)
            self.terminoTime.setDisabled(True)
            self.terminoTime.setTime(nextTime)
        else:
            self.inicioTime.setDisabled(False)
            self.terminoDate.setDisabled(False)
            self.terminoTime.setDisabled(False)
    
    def setWin(self):
        self.buttonSetOK.clicked.connect(self.win.addCompromisso)